# Generated by Django 3.0.8 on 2020-07-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_Pages', '0002_remove_facebookdatapages_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookdatapages',
            name='page_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
